### ISSUE TITLE
Deploying blueprint in unsupported region (eu-west-2)

### ISSUE THREAD

**Issue by dvito-mestag** [aws-quickstart/quickstart-biotech-blueprint#22]
Hi, I was wondering how it would be possible to deploy this stack in eu-west-2 (London), which is not among the 3 supported regions. I have tried to deploy it but I get an error right at the start:

`Template error: Unable to get mapping for RegionServiceSupport::eu-west-2::ConfigRules`

Is it possible to manually change any of the parameters? I have tried to disable config as well, but it didn't work.

**Comment by ajfriedman18** [comment]
Hi @dvito-mestag. The key areas to modify would be the Mappings section of https://github.com/aws-quickstart/quickstart-biotech-blueprint/blob/main/templates/biotech-blueprint-master.template.yaml. In particular, you would need to add `eu-west-2` to below Line 165-167 and below Line 175-177. They would look something like:

```
eu-west-2:
  ConfigRules: true
  Glacier: true
```

and 

```
eu-west-2:
  AMI: <ami-id in eu-west-2>
  InstanceType: m4.large
```

**Comment by davyto** [comment]
Thank you, that worked!

**Comment by dvito-mestag** [comment]
Thank you, that worked!
