### ISSUE TITLE
Architecture diagram is different from that of aws-quickstart / quickstart-aws-biotech-blueprint-cdk

### ISSUE THREAD

**Issue by helenxl** [aws-quickstart/quickstart-biotech-blueprint#23]
Is this repo out of date?
The architecture diagram and the template code refers to **two** VPCs (preClinical and Management), whereas [quickstart-aws-biotech-blueprint-cdk](https://github.com/aws-quickstart/quickstart-biotech-blueprint) has **three** VPCs (management, development and production).

**Comment by paulu-aws** [comment]
@helenxl Thanks for the question. Its best to use the CDK version going forward. We will be deprecating this repo soon.

**Comment by helenxl** [comment]
FYI. The link at the top of https://aws-quickstart.github.io/quickstart-aws-biotech-blueprint-cdk/ is pointing to this repo instead of the CDK version, and hence my confusion. Excerpt below:

> Visit our [GitHub repository](https://github.com/aws-quickstart/quickstart-biotech-blueprint) for source files and to post feedback, report bugs, or submit feature ideas for this Quick Start.

**Comment by paulu-aws** [comment]
Thanks for catching that. Will try and get that updated today.

**Comment by sshvans** [comment]
This is fixed.
